apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: docker-registry
  labels:
    app: docker-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-ui
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      automountServiceAccountToken: false
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:2.5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 250m
              memory: 256Mi
              ephemeral-storage: 500Mi
          env:
            - name: REGISTRY_TITLE
              value: "FreeCloud Docker Registry"
            - name: REGISTRY_URL
              value: "https://docker-registry.docker-registry.svc.cluster.local:5000"
            - name: SINGLE_REGISTRY
              value: "true"
            - name: DELETE_IMAGES
              value: "true"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: docker-registry
  labels:
    app: docker-registry-ui
spec:
  type: LoadBalancer
  selector:
    app: docker-registry-ui
  ports:
    - port: 5001
      targetPort: 80
      name: http
