apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: docker-registry
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: 30500
