apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terminal-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/freecloudinitiative/k3s-manifests.git'
    targetRevision: HEAD
    path: applications/terminal-gateway
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.digest
          value: "sha256:5008e435ddc5d4d3e5f1e0b1e88bf8bafa4992802fe38988d69e6197e69f5494"
        - name: imagePullSecrets[0].name
          value: zot-registry-pull-credentials
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
