apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terminal-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/freecloudinitiative/k3s-manifests.git'
    targetRevision: HEAD
    path: applications/terminal-gateway
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.digest
          value: "sha256:8c3718aabb822acc55df17fe545774e86272da892ec678ed51ee2c38786049f8"
        - name: imagePullSecrets[0].name
          value: zot-registry-pull-credentials
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
