apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-wave-health: all
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://zotregistry.dev/helm-charts
      chart: zot
      targetRevision: 0.1.122
      helm:
        valueFiles:
          - $values/infrastructure/zot-registry/values.yaml
    - repoURL: https://github.com/freecloudinitiative/k3s-manifests.git
      targetRevision: HEAD
      path: infrastructure/zot-registry
      ref: values
      directory:
        include: '{external-secrets.yaml,middleware.yaml,networkpolicy.yaml,service-account.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: zot-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
