apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-s3-credentials
  namespace: zot-registry
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: zot-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: access-key-id
      remoteRef:
        key: zot-registry
        property: s3-access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: zot-registry
        property: s3-secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-registry-auth
  namespace: zot-registry
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: zot-registry-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        users: "{{ .htpasswd }}"
  data:
    - secretKey: htpasswd
      remoteRef:
        key: zot-registry
        property: htpasswd
