apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: registry-auth
  namespace: zot-registry
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  basicAuth:
    secret: zot-registry-auth
    realm: Free Cloud Initiative Registry
    removeHeader: true
