replicaCount: 1

image:
  repository: mingrammer/flog
  tag: 0.4.3
  pullPolicy: IfNotPresent

format: json
delay: 1s
loop: true

resources:
  requests:
    cpu: 20m
    memory: 32Mi
    ephemeral-storage: 50Mi
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi

automountServiceAccountToken: false

