apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      The :latest image tag is mutable and unpredictable. Require digest or explicit version tags.
spec:
  validationFailureAction: Audit
  background: true
  skipBackgroundRequests: true
  rules:
    - name: require-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "An image tag is required."
        pattern:
          spec:
            =(ephemeralContainers):
              - image: "*:*"
            =(initContainers):
              - image: "*:*"
            containers:
              - image: "*:*"
    - name: validate-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using the ':latest' image tag is not allowed. Use an explicit version tag or digest."
        pattern:
          spec:
            =(ephemeralContainers):
              - image: "!*:latest"
            =(initContainers):
              - image: "!*:latest"
            containers:
              - image: "!*:latest"
