apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-store
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  conditions:
    - namespaces:
        - authentik
        - argocd
        - backend
        - frontend
        - monitoring
        - platform-database
        - valkey
  provider:
    vault:
      server: "https://openbao-active.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: openbao-server-tls
        key: ca.crt
        namespace: openbao
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets-openbao
            namespace: external-secrets
            audiences:
              - vault
