replicaCount: 1

image:
  repository: ghcr.io/prometheus-community/avalanche
  tag: main@sha256:8fd5c6fd8552b9e95e161dcd5c7acbe6d41c20655bc4aeade42ed25ae2eca3a0
  pullPolicy: IfNotPresent

avalanche:
  port: 9001
  gaugeMetricCount: 50
  seriesCount: 10
  labelCount: 5

serviceMonitor:
  enabled: true
  interval: 15s

resources:
  requests:
    cpu: 20m
    memory: 32Mi
    ephemeral-storage: 50Mi
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi

automountServiceAccountToken: false
