apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-credentials
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: api-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users: '{{ htpasswd .username .password }}'
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/traefik/api-auth
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/traefik/api-auth
        property: password
