apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  users: "<path:secret/data/traefik/api-auth#username>:<path:secret/data/traefik/api-auth#password>"
