image:
  tag: v3.3.2

deployment:
  kind: DaemonSet

ports:
  traefik:
    port: 9000
    expose:
      default: false
  web:
    port: 8000
    hostPort: 80
  websecure:
    port: 8443
    hostPort: 443

service:
  enabled: true
  type: ClusterIP

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 500Mi
