image:
  tag: v3.3.2

service:
  enabled: true
  type: LoadBalancer

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 500Mi
