apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/freecloudinitiative/k3s-manifests.git'
    targetRevision: HEAD
    path: applications/database-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.digest
          value: "sha256:f34a384348aea751104c65fcf35c1fa314f7d137fc4ff44580e73d3f32de098b"
        - name: imagePullSecrets[0].name
          value: zot-registry-pull-credentials
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
