apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: garage-rpc-password
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 64
  digits: 0
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc-secret
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshPolicy: CreatedOnce
  target:
    name: garage-rpc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        rpcSecret: '{{ .password }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: garage-rpc-password
