apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/freecloudinitiative/k3s-manifests.git'
    targetRevision: HEAD
    path: applications/api-gateway
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.digest
          value: "sha256:edb9fd02e41dbfd000756581012a6b6062d8c0bfea6addf04381b7d44047baac"
        - name: imagePullSecrets[0].name
          value: zot-registry-pull-credentials
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
