apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/freecloudinitiative/k3s-manifests.git'
    targetRevision: HEAD
    path: applications/api-gateway
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.digest
          value: "sha256:d3f8f2fa5ff2f0c3af7f7f0d8df4b344d2e1e678dcf899338ada60a8c3d50d4e"
        - name: imagePullSecrets[0].name
          value: zot-registry-pull-credentials
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
