apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  admin-user: "<path:secret/data/grafana#admin-user>"
  admin-password: "<path:secret/data/grafana#admin-password>"
