apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:

        - name: avalanche
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port={{ .Values.avalanche.port }}"
            - "--metric-count={{ .Values.avalanche.metricCount }}"
            - "--series-count={{ .Values.avalanche.seriesCount }}"
            - "--label-count={{ .Values.avalanche.labelCount }}"
          ports:
            - containerPort: {{ .Values.avalanche.port }}
              name: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
