expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls-cert
  ingress:
    hosts:
      core: harbor.freecloudinitiative.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: traefik

externalURL: https://harbor.freecloudinitiative.com

existingSecretAdminPassword: harbor-admin-secret
secretKeyAdminPassword: secret

portal:
  nodeSelector:
    node-tier: high-memory
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

core:
  nodeSelector:
    node-tier: high-memory
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

jobservice:
  nodeSelector:
    node-tier: high-memory
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

registry:
  nodeSelector:
    node-tier: high-memory
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

trivy:
  nodeSelector:
    node-tier: high-memory

exporter:
  nodeSelector:
    node-tier: high-memory

database:
  internal:
    nodeSelector:
      node-tier: high-memory

redis:
  internal:
    nodeSelector:
      node-tier: high-memory
