name: PR Checker
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master]
  workflow_dispatch:

jobs:
  check:
    uses: freecloudinitiative/.github/.github/workflows/k3s-pr-checker.yml@2816605944e9c3355e401d527f7f725b05b71ce5
    secrets: inherit
